### ISSUE TITLE
Diagrama de clases

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#100]
Empezar a completar la parte diseño del anexo.

**Comment by Tulmot** [comment]
Hecho este diagrama de flujo:
![imagen](https://user-images.githubusercontent.com/30071903/34908797-19259c98-f896-11e7-87d8-7f6f2fa6b62b.png)

Es uno que he hecho básico falta poner el tipo y alguna cosa más pero para saber si así es la idea

**Comment by alvarag** [comment]
Supongo que querías decir diagrama de clases. Repasa los apuntes de Carlos de UML, la herencia no está expresada y las agregaciones se encuentran en el lado contrario al que deberían.
En cuanto a los tipos, faltarían de definir entiendo porque en todos pones type y no tienen parámetros de entrada

**Comment by Tulmot** [comment]
Entiendo que así estaría bien el diagrama de clases.

![untitled diagram](https://user-images.githubusercontent.com/30071903/34989997-c5ef5178-fac4-11e7-9004-cef2a75632d2.png)

**Comment by alvarag** [comment]
Hay cosas que siguen sin gustarme:

- El constructor debería recibir argumentos, sino quítalos.
- HomogeneusEnsemble es abstracta la clase.
- Lo que hay en HomogeneusEnsemble yo no lo repetiría en las subclases
- Además añadiría las dependencias que tienes de clases de Sklearn: tus clases heredan de ellas.

Si ves que se complica el diagrama al poner las clases de Sklearn de las que heredan, puedes hacer este diagrama por un lado y luego uno general (sin métodos) con el diagrama general.

**Comment by Tulmot** [comment]
El constructor lo he quitado porque tenías muchos argumentos y sino las clases me quedaban muy anchas.
Por lo que he visto de las clases abstractas se heredan los métodos, por lo que de las clases he quitado los atributos y he heredado los métodos de la clase abstracta.

![classdiagram](https://user-images.githubusercontent.com/30071903/35035605-3d38a948-fb72-11e7-8057-240bd51dc9d5.png)

Las dependencias de las clases de Sklearn como has dicho haré un diagrama a parte general, ya que veo que se entenderá mejor con dos diagramas que uno con todo.
