### ISSUE TITLE
Mejorar notebooks

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#103]
En los notebooks, lo primero que debería aparecer es una celda de Markdown con un título, autor, puede que el logo de la UBU...
Después una descripción de lo que hace el notebook.
Luego ya el notebook en sí.

Además mejoraría alguna cosa, por ejemplo en el de las banderas, flags2.arff (¿por qué el 2?), y además por qué solo se saca la distancia de hamming? Mejor sacar varias medidas de multi-label

**Comment by alvarag** [comment]
Tampoco me convencen los nombres:

- Real data sets -> Example with real ML data set.
- Test with iterations -> Example of ensembles classifiers
- Test without iterations -> Example of base classifiers

**Comment by Tulmot** [comment]
He calculado las siguientes distancias:

![imagen](https://user-images.githubusercontent.com/30071903/34918665-88a813c8-f956-11e7-902f-d1f14f96bafd.png)

**Comment by alvarag** [comment]
Son medidas, no distancias.

Errata: "Hamming Loss"

**Comment by Tulmot** [comment]
y algun ejemplo de distancias, es que poniendo distances multilabel en google encuentro esas

**Comment by alvarag** [comment]
Lo que quieres utilizar para "validar" los métodos son medidas, ¿para qué quieres distancias?

**Comment by Tulmot** [comment]
Perdón entendí mal, que sacaba medidas y queríamos distancias...

f1_score por ejemplo valdría como medida no?

**Comment by Tulmot** [comment]
Así estaría correcto no?
![imagen](https://user-images.githubusercontent.com/30071903/34950161-a837daae-fa12-11e7-82eb-b79846420b06.png)
