### ISSUE TITLE
Sonarqube

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#104]
Utilizar la aplicación sonarqube para ver que no hay código duplicado

**Comment by Tulmot** [comment]
He estado mirando como funciona Sonarqube, en el uso online, la cosa es que no se como hacer para introducir mi proyecto, he estado siguiendo el tutorial de https://about.sonarcloud.io/get-started/ pero el último paso:
![image](https://user-images.githubusercontent.com/30071903/34980604-56f31c88-faa5-11e7-8bb4-563744e11441.png)
No se exactamente donde tengo que ejecutar eso.

**Comment by alvarag** [comment]
Puedes analizar el código online "enganchando" tu proyecto Git con SonarQube (o al menos antes se podía).

Regístrate en: https://about.sonarcloud.io/ y sigue los pasos.

**Comment by Tulmot** [comment]
He conseguido hacer que funcione pero no se si esta bien 
![image](https://user-images.githubusercontent.com/30071903/35265876-bdbf03f6-0021-11e8-8e09-4ccced17e22c.png)
Porque por lo que pone a la derecha solo analizado 393 lineas de código y tengo mas.

**Comment by alvarag** [comment]
Vete a la pestaña Code, supongo que ahí podrás ver los ficheros analizados.

**Comment by Tulmot** [comment]
Me salen cosillas en los 3 base y en homogeneous, en los ensemble en verdad como solo tienen el constructor y el validate_estimator por eso supongo que no tendrán nada.
En casi todos los code me dice esto:
Rename this parameter "X" to match the regular expression ^[_a-z][a-z0-9_]*$.

**Comment by alvarag** [comment]
Supongo que tras haber cursado _Procesadores del Lenguaje_ sabrás interpretar la expresión regular que te recomienda utilizar.
Como te dije, no todas las recomendaciones que da Sonar Qube debemos aplicarlas. En el anexo en el que hables de cómo se ha aplicado SonarQube y el resultado, comentas el por qué no se ha seguido esa recomendación.

**Comment by alvarag** [comment]
Por cierto, si son públicos los datos (es decir, podemos verlo desde una URL), ponla por aquí.

**Comment by Tulmot** [comment]
mmm vale entonces tengo que explicar porque no sigo esa recomendación, entonces entiendo que no necesito cambiar nada.

Aquí podéis verlo:
https://sonarcloud.io/dashboard?id=sklearn

**Comment by alvarag** [comment]
Eso es, la valoración global es buena "A". Si vas a código si que te ha analizado todo, tienes unas mil líneas en total pero sin comentarios son las 393 que aparecen (por eso te marca el proyecto como XS).

Esto es un buen indicativo de que el código (siempre y cuando funcione bien), esta bien escrito.

Recuerda incluir todo esto en el Anexo de manual del programdor: cómo has incluido tu proyecto en SonarQube, la URL, y los comentarios.
