### ISSUE TITLE
Gráfica Ramdon Oracle

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#105]
La gráfica dibujada en Random Oracle no es como debería, el fallo puede estar en el predict_proba

**Comment by Tulmot** [comment]
Para comprobar a ver si lo hace bien lo que hecho ha sido lo que me ha recomendado Alvar, he creado un pequeño conjunto de 20 datos, y he pintado con amarillo los dos oraculos seleccionados. 
![imagen](https://user-images.githubusercontent.com/30071903/35062079-5dc4eef0-fbc3-11e7-824c-d8e9aa5033e6.png)

La división entiendo que la hace mal, pero nose de que manera podría comprobar donde esta el fallo.
Acabo de subir el notebook de prueba donde están los otros notebook por si quereis mirar alguna cosa (Luego lo borraré).

**Comment by alvarag** [comment]
Solo con esa gráfica no se puede saber qué es lo que está ocurriendo.
¿Has hecho los pasos que te dije?

- Revisar que el conjunto de entrenamiento de cada uno de los árboles es distinto: las que están más cerca de una de las instancias amarillas deben utilizarse para el train de ese árbol y las otras para el otro.
- Clasificar una instancia que sepas que su instancia más cercana es uno de las dos de referencia: revisar si se llama al predict de dicha instancia.

Es todo cuestión de ir viendo paso a paso lo que hace tu algoritmo y si se corresponde con lo que debería.

Lo difícil no suele ser implementar algoritmos, sino comprobar y validar que funcionan como se espera.

**Comment by alvarag** [comment]
Por lo poco que he visto, si es que he entendido bien tu código _muy_poco_documentado_ el problema lo tienes en el _fit_ (o al menos uno de ellos).

```Python
def train(nearest_oracles):
            """Entrenamos cada uno de los oraculos """
            oracle_near = np.asarray(nearest_oracles).astype(bool)
            """Si no es multilabel"""
            if not is_multilabel(y):
                self._multilabel = False
                return self.base_estimator.fit(X, y)
            else:
                self._multilabel = True
                Xp = X[oracle_near, :]
                yp = y[oracle_near, :]
                return self.base_estimator.fit(Xp, yp)
```

Estas devolviendo siempre el mismo clasificador entrenado con distinto conjunto de datos, así que solo tienes en verdad un clasificador. Tienes que tener tantos clasificadores como "oráculos" (para que me entiendas). Pensé que estaba claro.

**Comment by Tulmot** [comment]
Pero entonces lo que no entiendo yo calculo los oráculos más cercanos, entonces pensaba que al llamar al fit yo ya le paso en ese conjunto los mas cercanos a cada uno de los oráculos, entonces por lo que dices debería tener dos matrices cada una de ellas tendrá un oráculo y luego los demás datos los voy introduciendo en la matriz que contiene el oráculo más cercano a ese dato.

No se si me explico.

Porque sino si tengo la matriz de los oráculos más cercanos (como lo tengo ahora)  por mucho que llame a los clasificadores que sean, si siempre le paso los mismos datos me devolverán lo mismo.

Es decir Xp e yp debería calcularlo de otra manera supongo, por eso lo que he dicho al principio.

**Comment by alvarag** [comment]
Imagina que tienes dos "oráculos" más cercanos, esto implica que:

- Vas a tener dos clasificadores base.
- Cada clasificador base se entrena con las instancias más cercanas a cada uno de ellos. A esto me refiero a que tienes como "dos conjuntos de entrenamiento". Cada clasificador base se entrena con un conjunto distinto.
- En el fit tienes que ver la instancia a predecir de qué "oráculo" es el más cercano y llamar a su predict.

Todo eso de arriba no tengo claro que lo estés haciendo bien, tal vez si.

Pero lo que me preocupa es que el método train no esta funcionando como tu esperas.

```Python
self.base_estimator.fit(Xp, yp)
```

Esa línea está devolviendo siempre el mismo clasificador, lo que pasa es que le estás entrenando con cosas distintas: pero siempre es el *mismo* objeto. Tu lo que quieres es tener dos (o los que sean) objetos distintos de la clase base_estimator y entrenarlos.

**Comment by alvarag** [comment]
En HomogeneusEnsemble estás ya haciendo copia de clasificadores base, así que con la función que utilizas allí debería serte fácil hacerlo
