### ISSUE TITLE
Añadir técnicas y herramientas

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#124]
Añadir nuevas técnicas y herramientas como por ejemplo Graphviz, Zenhub o Python

**Comment by Tulmot** [comment]
Sonarqube también sería una herramienta no?

**Comment by alvarag** [comment]
Excato

**Comment by Tulmot** [comment]
Una pregunta Python por ejemplo he cogido la información de la página oficial https://www.python.org/about/, entonces nose si como abajo de las técnicas y herramientas siempre pongo las páginas oficiales donde encontrar esa herramienta si haría falta citarla...o como ya pongo la url, no es necesario.

**Comment by jjrodriguez** [comment]
Si pones una url directamente en el texto o como nota al pie, entiendo que no hace falta poner además una referencia.

Pero en el caso de Python sí que creo que debería aparecer alguna entrada en la bibliografía, por ejemplo algún libro.

Por cierto, en la bibliografía no te aparecen las urls, y en alguna entrada es crucial. Las puedes incluir en el fichero bib con un campo 
  note = {\url{http://...}}
