### ISSUE TITLE
Trabajos relacionados

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#126]
Trabajos relacionados como por ejemplo:

-Librerías ensemble
-Librerías de aprendizaje automático
-Servicios de computación en la nube

**Comment by jjrodriguez** [comment]
Añadir específicos de multi-label:

- Mulan: http://mulan.sourceforge.net/
- scikit-multilearn: http://scikit.ml/
- mldr: https://cran.r-project.org/web/packages/mldr/index.html

**Comment by Tulmot** [comment]
Estos 3 podrías meterlos en librerías de aprendizaje automático o mejor crear otro apartado de librerías para aprendizaje multi-label?
