### ISSUE TITLE
Hacer pruebas

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#127]
Hacemos pruebas para ver el correcto funcionamiento.
Las hacemos sobre DecisionTreeClassifier comparado con nuestros 3 algoritmos mediante la validación cruzada.

**Comment by Tulmot** [comment]
Algo así os referiais?
![imagen](https://user-images.githubusercontent.com/30071903/35344274-08166ab4-012d-11e8-9486-e7c2a9efb96c.png)

**Comment by jjrodriguez** [comment]
Sí, pero con el valor medio en vez de la suma.

Habría que decir qué medida se está calculando. Mejor si se calculan varias.

**Comment by Tulmot** [comment]
No entiendo muy bien a que te refieres con la medida que se esta calculando...
En este caso por ejemplo seria validación cruzada y luego entiendo que usase mas medidas como las que tengo en los otros notebooks?

**Comment by jjrodriguez** [comment]
Con esos números, ¿cuál es el mejor método y cuál es el peor? Si no dices si son errores o precisiones, o lo que sea...
Ya habías hecho un notebook en el que calculabas varias medidas (algunas de las cuales eran distancias)

**Comment by Tulmot** [comment]
Esto es un ejemplo:
```
df = pd.DataFrame({
   'col1': ['Item0', 'Item0', 'Item1', 'Item1'],
   'col2': ['Gold', 'Bronze', 'Gold', 'Silver'],
   'col3': [1, 2, np.nan, 4]
})
```
Estaba intentando hacer una tabla con los resultados, el problema que yo tengo una lista de listas es decir yo tengo: 
`a=[['Item0', 'Item0', 'Item1'],['Gold', 'Bronze', 'Gold'],[1, 2, np.nan]]`

Entonces nose de que manera hacerlo para ir recorriendo cada una de las listas y meterlas en el dataframe, si me podeis dar alguna idea.

**Comment by Tulmot** [comment]
Vale ya lo he solucionado
![imagen](https://user-images.githubusercontent.com/30071903/35455656-10f4b954-02d3-11e8-9e5f-a939860e232d.png)
Luego arriba pondre un comentario que por ejemplo esta medida es accuracy y explico que hace esa medida
Solo tiene 2 conjuntos de datos para que tardara poco en ejecutarlo.
