### ISSUE TITLE
Anexos: Diseño arquitectónico

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#130]
Vamos acabar la parte de diseño del anexo realizando la parte de diseño arquitectónico, en la que se mostrará la estructura de nuestro proyecto.

**Comment by Tulmot** [comment]
Debería dibujar un equema de como esta estructura o  con la explicación valdría?

Es que en la parte del manual del programador en la estructura de directorios, ya lo explicado.

**Comment by alvarag** [comment]
Aquí tienes que explicar el diseño arquitectónico de tu desarrollo, en tu caso es solamente un paquete. Para darle un poco de "vistosidad" al diagrama, deberías al menos dibujar también el paquete de sklearn.

**Comment by Tulmot** [comment]
El diagrama tendría este aspecto:
![imagen](https://user-images.githubusercontent.com/30071903/35520590-b9779056-0517-11e8-8029-b1e60ce76c34.png)
Y luego explicaria cada paquete y sus referencias a los otros paquetes.

No se si así esto sería correcto.

**Comment by alvarag** [comment]
SRC no es un paquete, así que lo quitaría. Dejaría sklearn-ubu y cómo se relaciona con sklearn (el paquete).

**Comment by Tulmot** [comment]
Pero y dentro del paquete sklearn, tendría que poner clases que llamo como BaseEstimator o BaseEnsemble o eso no haría falta?

**Comment by alvarag** [comment]
Es diseño arquitectónico, los detalles para el de clases y secuencias

**Comment by Tulmot** [comment]
Con algo tán básico como esto entiendo que valdría entonces.
![imagen](https://user-images.githubusercontent.com/30071903/35523666-a7592e18-051f-11e8-8f02-6e2a87718414.png)

**Comment by alvarag** [comment]
Si, de hecho haría la relación de sklearn-ubu con sklearn y listo
