### ISSUE TITLE
Problemas en notebooks

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#131]
En DT vs Ensembles:

- 4ª celda: TypeError: __init__() got an unexpected keyword argument 'n_neighbors'
- Los parámetros que "dirigen" el funcionamieto del algoritmo, como puede ser el nº de grupos en la validación cruzada debería aparecer al inicio del notebook (esto es aplicable a todos los notebooks).
- _n_samples_ también debería ser un parámetro y no estar "a pelo" en el código.
- Le falta al inicio información de autores, qué va a hacer, etc.

En Graphics:

- El tema de los parámetros como en el otro.
- Dejar "limpio" el código con solo los clasificadores que usas.
- Al inicio le falta...

En general:

- Sigue poniendo Índice en vez de Table of contents... ¡cosas que te comenté ya en una issue y que no se han corregido pese a haber cerrado la issue!

**Comment by Tulmot** [comment]
Lo último ya esta bien, que se me había olvidado subirlo a GitHub, perdón.

**Comment by Tulmot** [comment]
Una duda estaba con lo de los paremetros que hay que inicializarlos al inicio del notebook.
En el notebook de Examen with real ML, el unico parámetro sería el de la validación cruzada, entonces nose si haria falta poner ese al principio o en este caso no.

**Comment by alvarag** [comment]
Es preferible que todos los notebooks se comporten de un modo similar, para facilitar al usuario su uso.
Así que aunque sea solo un parámetro, mejor arriba.
