### ISSUE TITLE
Memoria correcciones

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#132]
Creo que no tienes la última versión de la memoria subida, porque he visto muchos fallos que ya habíamos visto. Cuando la tengas me lo dices por aquí y la reviso.

[memoriaC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1674357/memoriaC.pdf)

**Comment by Tulmot** [comment]
La subi ayer actualizada, supongo que la revisarías algo antes, de todas formas he visto alguna cosa que me falta corregir todavía, así que mañana que lo deje todo bien, la vuelvo a subir y te aviso.

**Comment by alvarag** [comment]
No, la versión que he revisado me la he bajado minutos antes de crear la issue

**Comment by Tulmot** [comment]
A mi por ejemplo los objetivos me aperecen los 3 algoritmos todos como 1 objetivo, si es verdad que la introducción tengo que cambiar alguna cosa.

Nota: solo he subido el .pdf los .tex no

**Comment by Tulmot** [comment]
Lo acabo de volver a subir con un par de cambios que me faltaban en la introducción, el resto lo tenía ya bien.

Te la envío también al correo por si acaso, pero no se porque tienes otra versión.

**Comment by alvarag** [comment]
Adjunto comentarios:

[anexosC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1678296/anexosC.pdf)
[memoriaC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1678297/memoriaC.pdf)

**Comment by Tulmot** [comment]
En una de las correciones que me has puesto en  las bibliografías
```
Para evitar esto, donde se incluye el paquete hyperref, cámbialo por esto:
\PassOptionsToPackage{hyphens}{url}\usepackage{hyperref}
```
Sería en el .tex de la memoria, que en la línea pone:

> \usepackage[colorlinks]{hyperref}

o donde se incluye el paquete?

**Comment by alvarag** [comment]
Cambias el usepackage que tienes por lo que te he puesto (si quieres puedes mantener [colorlinks]
