### ISSUE TITLE
Documentación Random Oracle

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#133]
Estoy mejorando la parte del concepto teórico  de Random Oracle, y estaba mirando un poco la documentación que me paso Juan José

[pardo-rodriguez-diezpastor-garciaosorio_random-oracles-regression-ensembles.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1682269/pardo-rodriguez-diezpastor-garciaosorio_random-oracles-regression-ensembles.pdf)

Y en la sección 11.2 Random Oracles, sobre en que consiste el entrenamiento del modelo de RO. Y de las 3 partes la última:

> For each subset of the training data, build a model. The Random Oracle model is
> formed by the pair of models and the oracle itself.

La segunda parte de que esta formado por un par de modelos y el propio oráculo, no se muy bien a que se refiere con lo de un par de modelos. Si me podrías explicar ese concepto.

**Comment by jjrodriguez** [comment]
En tu caso los modelos son árboles. Y son un par porque seleccionabamos dos instancias aleatoriamente, tu lo has hecho para que funcione con un número variable.

**Comment by Tulmot** [comment]
Vale gracias.
