### ISSUE TITLE
Anexos. Estudio de viabilidad

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#137]
En la sección de plan de proyecto, hacer la parte de estudio de viabilidad, con sus correpondientes viabilidad económica y legal.

**Comment by Tulmot** [comment]
Sobre la viabilidad legal, entiendo que hay que hablar sobre las licencias de la librerías, entonces yo de esas librerías tendría:
-numpy
-matplotlib
-sklearn

con esas valdría no?

**Comment by jjrodriguez** [comment]
Está graphviz para dibujar los árboles., ¿no?

**Comment by Tulmot** [comment]
no me acordaba de esa, vale pues esas 4

**Comment by Tulmot** [comment]
sobre la licencia para graphviz he encontrado esto:
https://www.graphviz.org/license/

Pero no se muy bien donde pone que licencia tiene...

**Comment by jjrodriguez** [comment]
Pues entiendo que "Common Public License Version 1.0"

Una cosa es la aplicación graphviz y otra el módulo python qué usas para acceder a esa aplicación. Y pueden tener licencias distintas.

Desde el punto de vista de la legalidad entiendo que lo que importa es la del módulo python

De acuerdo a https://pypi.python.org/pypi/graphviz y https://github.com/xflr6/graphviz/blob/master/LICENSE.txt la licencia es MIT.
