### ISSUE TITLE
Anexos. Especificación de requisitos

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#138]
Se espefican los requisitos, y se hacen los diagramas de caso de uso para ellos.

**Comment by Tulmot** [comment]
Haciendo las tablas de los casos de uso, me he fijado en otros tfg, y tengo duda sobre que he visto solo hacen tablas si un requisito contiene otro, es decir, si por ejemplo tengo:

- RF1
-     RF1.1
-         RF1.1.1

- RF2
-     RF2.2

En el primer caso se harían tablas en los caso RF1 y RF1.1, mientras que en el segundo caso solo en RF2, entonces como yo mis casos son como el segundo...nose si deberías hacer las tablas de RF2 y RF2.2 o solo RF2.

No se si se me ha entendido

**Comment by alvarag** [comment]
Hazte a la idea de que cada caso de uso (de los diagramas), debería tener su tabla de definición para saber qué es lo que hace dicho caso de uso. Así que deberías hacer de primer nivel y segundo.
