### ISSUE TITLE
Notebook DT vs ensembles

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#141]
Hacer conjuntos de datos más fáciles para que sea mejor la precisión.

Y añadir alguna medida.

**Comment by Tulmot** [comment]
El primer conjunto ya me saca una precision bastante buena entiendo que asi valdría no?
![imagen](https://user-images.githubusercontent.com/30071903/35769747-f869f6f4-090f-11e8-8bc3-5c03f656329a.png)

**Comment by jjrodriguez** [comment]
Mejor.

No tenía claro que se estaba midiendo, si fuera una precisión (accuracy) promedio no deberíamos tener valores muy por debajo de 0.5.

De acuerdo a la documentación: http://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html

_In multilabel classification, this function computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true._

Entiendo que vendría ser la medida que se denomina "exact match".

Podrías probar con alguna de las medidas que usabas en https://github.com/Tulmot/Sklearn-Multilabel/blob/master/src/Example%20with%20real%20ML%20data%20set.ipynb

**Comment by Tulmot** [comment]
Intento meter las medidas que tengo en ese notebook, pero me da este error:

> ValueError: Target is multilabel-indicator but average='binary'. Please choose another average setting.

No entiendo muy bien el error, osea me dice que es multi-label pero el promedio binario...
