### ISSUE TITLE
Correcciones memoria

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#142]
[memoriaC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1700167/memoriaC.pdf)

**Comment by Tulmot** [comment]
Sigo sin entender porque las versiones que tu ves son distintas a las mías por ejemplo aspectos relevantes si lo tengo:
![image](https://user-images.githubusercontent.com/30071903/35909382-b85b3d66-0bf3-11e8-8c23-1bf72d5ce7de.png)

Es decir, errores que me mandas corregir, ya están corregidos. Entonces no se cual puede ser la razón...igual que otras partessi que me aparecen en el pdf subido, pero por lo que veo a ti no...

Así que no se que hacer a parte de subirlo os lo envío por correo o algo porque sino, me vais a corregir cosas que ya están corregidas.

**Comment by alvarag** [comment]
El archivo `memoria.tex` esta actualizado hace 10 días, supongo que ese será el motivo.

**Comment by Tulmot** [comment]
pero si yo me lo descargo en un ordenador(el mio no) y se me ve bien..es raro que a mi se me vea bien y a ti no.

A la tarde cuando llegue a casa actualizo todos los .tex por si acaso.

**Comment by alvarag** [comment]
Yo siempre me bajo tu código y lo cmpilo con LaTeX, no cojo el PDF que tienes subido. Siempre que hagas cambios en la memoria deberías subir el tex

**Comment by Tulmot** [comment]
Ahh vale, entonces ese es el problema...que los latex los actualizo de vez en cuando no cada vez que realizo un cambio.
Pensaba que mirabas el pdf, ahora ya lo entiendo.

**Comment by alvarag** [comment]
Lo importante es que en el control de versiones tengamos actualizados los archivos ORIGINALES, es decir, los .tex.

**Comment by Tulmot** [comment]
Vale pues hoy a la hora de comer subo todos.

**Comment by Tulmot** [comment]
Ya estan todos los tex, si podeis mirarme las secciones de aspectos relevantes y trabajos relacionados a ver si lo añadido esta bien.

**Comment by jjrodriguez** [comment]
Algunos comentarios en la memoria: [memoriaC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/blob/master/Documentaci%C3%B3n/memoriaC.pdf)

**Comment by Tulmot** [comment]
Lo que me has subido aqui es lo mismo que esta en la carpeta de documentación?

**Comment by jjrodriguez** [comment]
No lo he subido aquí, he puesto un enlace al fichero de la carpeta documentacion.
