### ISSUE TITLE
Correciones y completar anexos

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#144]
Correciones indicadas en la tutoría, y también falta añadir alguna parte en alguna sección

**Comment by Tulmot** [comment]
En la parte de viabilidad:
![imagen](https://user-images.githubusercontent.com/30071903/35932742-c5cb2052-0c38-11e8-86cd-af0ab4f0734d.png)
He puesto una url de donde he cogido los porcentajes...mi duda es si ponerla o no, y que como se sale de los márgenes nose porque puede ser, porque en anexos he añadido 

> \PassOptionsToPackage{hyphens}{url}
> \usepackage[colorlinks]{hyperref}

**Comment by alvarag** [comment]
Lo puedes poner como pie de página, para que quede más pequeño

**Comment by alvarag** [comment]
Asegúrate de subir la última versión de todo lo que hagas hoy. Mañana intentaré hacer una última revisión general.

**Comment by Tulmot** [comment]
vale, voy acabar conclusiones, el resumen, el abract y a ver si para la noche lo tengo todo.

Esta tarde estareis alguno por el despacho?

**Comment by alvarag** [comment]
Yo no, tengo que dar un curso en Económicas

**Comment by Tulmot** [comment]
Es que estaba mirando los warning  al compilar la memoria que me dijiste y este

> Font shape `OT1/cmr/bx/sc' undefined(Font) using `OT1/cmr/bx/n' instead
> Replacing `OT1/cmr/bx/sc' by(spanish) faked small caps

Me sale en las lineas :
```

% Castellano
\usepackage[spanish,es-tabla]{babel}
\selectlanguage{spanish}

Y no encuentro por internet como corregirlo y, no entiendo muy bien que me dice que tengo reemplazar spanish...
```

**Comment by alvarag** [comment]
No le des importancia a todos los warning de LaTeX, que da demasiados ;)

**Comment by Tulmot** [comment]
Ya esta todo actualizado notebooks memoria y anexos.

Falta el sprint de esta semana porque hasta que no acabe todas las tareas no puedo hacerlo.

Y lo que queda hasta el lunes lo dedicare al de las gráficas multi-label y luego las correciones que me digais

Para lo de la entrega ya os comentare si tengo alguna duda.

**Comment by alvarag** [comment]
Pequeñas cosas de la memoria: 
[memoriaC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1711260/memoriaC.pdf)

**Comment by jjrodriguez** [comment]
Comentarios a los anexos: [anexosCC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/blob/master/Documentaci%C3%B3n/anexosCC.pdf)

**Comment by Tulmot** [comment]
Estaba con la memoria y en lo de añadir imágenes, en los links que me habeis añadido:
https://www.sciencedirect.com/science/article/pii/S0031320307000027
https://www.sciencedirect.com/science/article/pii/S0031320304001074
He estado mirando y no he visto ninguna tabla o imágenes que los compare...

**Comment by Tulmot** [comment]
la parte de usar usar \chapter[corto][largo] para que el texto de la cabecera sea más corto
que me lo has puesto en el apendice D de documentación técnica de programación
no estoy seguro de donde debería ponerlo...si en anexos.tex o en el tex de capitulo del manual del programador

**Comment by jjrodriguez** [comment]
En el fichero"`D_Manual_programador.tex`, sustituye la línea

`\apendice{Documentación técnica de programación}`

por

`\chapter[corto]{Documentación técnica de programación}`

donde `corto` es el nombre reducido.

**Comment by Tulmot** [comment]
vale gracias
