### ISSUE TITLE
Dejar finalizado el repositorio

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#146]
Recuerda que el repositorio es tu tarjeta de visita, debes hacer:

- Poner topics y descripción general a tu proyecto.
- Mejorar un poco el README, indicando lo que hay en cada carpeta y cómo ejecutarlo por ejemplo.
- Crear una release con todo tu código (sólo código y no docuemntación): https://help.github.com/articles/creating-releases/
- Invitar al repositorio a la cuenta de correo que tiene el tribunal.

**Comment by Tulmot** [comment]
En el readme, con ejectutarlo te refieres a los notebooks?

**Comment by jjrodriguez** [comment]
Subí mis comentarios a la carpeta Documentación y están incluidos en los ficheros comprimidos, habría que quitarlos.

**Comment by Tulmot** [comment]
vale
