### ISSUE TITLE
Semilla

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#26]
Hacer la semilla correctamente

**Comment by Tulmot** [comment]
Uso la semilla en la clase el problema en el metodo donde calculo el aleatorio para elegir los vecinos molestones con la funcion
"np.random_state.randint(0, tam,self.n_neighbors)"
Donde tam es el tamaño de las instancias, y n_neighbors es los vecinos molestones que quiero elegir, el aleatorio me devuelve repetidos.

**Comment by jjrodriguez** [comment]
Si no quieres repetidos, puedes probar con `random_state.choice(tam, self.n_neighbors, replace=False)`

**Comment by Tulmot** [comment]
Vale si me sirve, muchas gracias
