### ISSUE TITLE
Función predecir probabilidades

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#29]
Nueva función en la clase que nos predice la probabilidades

**Comment by Tulmot** [comment]
La hecho pero tengo dudas de que es te bien, porque lo que me devuelve creo que no es lo que me tendría que devolver

**Comment by alvarag** [comment]
A mi me está dando un error al ejecutarlo, no sé si porque no está la última versión... No obstante, ¿por qué dices que no está funcionando correctamente?

**Comment by Tulmot** [comment]
a mi me funciona bien y esta subido lo último
![imagen](https://user-images.githubusercontent.com/30071903/32334693-6b3e95b8-bfeb-11e7-8ba3-f9cde0a8ed77.png)
Me imprime una matriz de esta manera...y según entendí tenia que salir valores entre 0 y 1, como por ejemplo 0.5, no todo 0 o 1.

**Comment by alvarag** [comment]
Si le pides clasificar una instancia, te va a devolver un array de ceros y unos donde cada "1" representa que esa clase está activa y donde cada "0" representa que no lo está.
Si le pides probabilidades te dará entre 0 y 1, ¿entendido?

**Comment by Tulmot** [comment]
Vale vale, ya lo entendido todo bien gracias
