### ISSUE TITLE
Correcciones de estilo y mejoras al código DN

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#37]
- Según he visto en la guía de estilo PEP-8, se desaconseja el uso de guiones en los nombres de paquete, mejor utilizar guión bajo: https://www.python.org/dev/peps/pep-0008/#package-and-module-names

- Algunas variables de la clase deberían ser privados, ej: rnd_dimensions y rnd_neighbors

- Al igual que has hecho con las variables y nombres de métodos, sería interesante que los comentarios principales de la clase (el de cabecera, fit y test) estuvieran en inglés. Si es un problema el idioma nos lo dices.

- Utiliza el chequeador de sintaxis de PEP8 online para que te acostumbres a seguir el estilo de ahora en adelante: http://pep8online.com/

**Comment by Tulmot** [comment]
Todo corregido

**Comment by alvarag** [comment]
Un detalle de estructura del proyecto, yo haría:

- carpeta src (para código)
- carpeta doc (para memoria)

En la carpeta src metes el paquete sklearn_ubu y ahí mismo dejas el notebook para que puedas importar el paquete sin problemas. Además sirve a modo tutorial para quien quiera aprender a usarlo
