### ISSUE TITLE
Pasar un conjunto de datos reales a DN

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#39]
Le pasamos un conjunto de datos reales a nuestro DN.
Como el datasets que usaremos esta en un archivo .arff también tenemos que aprender como abrir un .arff en python

**Comment by Tulmot** [comment]
Instalado arff, muestra el archivo, ahora hay que ver como pasarselo a la clase para que funcione correctamente

**Comment by Tulmot** [comment]
Cuando tengo archivo leido para pasarselo al metodo, tengo que separar antes los datos( las X) y las clases (Y), sería asi?

**Comment by jjrodriguez** [comment]
Sí, hay que dividir el conjunto de datos..

**Comment by Tulmot** [comment]
Para dividirlo tengo que hacer manualmente, o tiene que ser automáticamente, es decir, en el ejemplo de las banderas tengo que decirle que las últimas 7 columnas son las clases y las primeras los datos, o de alguna manera el tendría que saber que las 7 últimas columnas son las clases?

**Comment by alvarag** [comment]
Hay diversas opciones:

- En Mulan hay un xml donde define el nombre de los atributos que forman parte de la clase: podría leer el xml (por ejemplo usando: https://docs.python.org/2/library/xml.etree.elementtree.html)
- En Meka lo que hacen es poner junto al nombre "-C xxx" donde xxx es el número de clases que hay en el dataset (ej: @relation 'Enron: -C 53', indica que los 53 primeros atributos del dataset son clases).
- Hacerlo de manera manual en un primer momento y ya lo haremos automático más adelante
