### ISSUE TITLE
Hacer funcional el método nearest_neighbor()

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#40]
Conseguir que el método sea más rápido al ejecutarse, es decir no usar dos bucles for

**Comment by Tulmot** [comment]
Funciona con un for, en vez de con dos, falta conseguir que no haga falta ningun for

`from sklearn.metrics.pairwise import euclidean_distances`
`x=np.array([[1,2],[2,4],[2,2]])`
`y=np.array([[1,2]])`
`z=np.array([[2,2],[2,4]])`
`print(x,y)`

`#No se puede trabajar con arrays de una dimension por eso [t]`
`euc_dis_func = lambda t: euclidean_distances([t],y)`
`vfunc = np.apply_along_axis(euc_dis_func,1,x).argmin()`

`#El problema es que no le pasamos x en ningun momento`
`#dn_nn = lambda inst : np.apply_along_axis(euc_dis_func,1,inst).argmin()`
`#np.apply_along_axis(dn_nn,1,z)`

**Comment by Tulmot** [comment]
`import numpy as np`
`from sklearn.metrics.pairwise import euclidean_distances`
`x=np.array([[1,2],[2,4],[2,2]])`
`z=np.array([[2,2],[2,4]])`
`euc_dis_func = lambda t: euclidean_distances([t],x).argmin()`
`dn_nn = lambda inst : np.apply_along_axis(euc_dis_func,1,[inst])`
`m_nearest=np.apply_along_axis(dn_nn,1,z)`
`m_nearest`

`m_neighbors = np.zeros(len(x))`
`vecinos = lambda near : m_neighbors[near]=1`
`prueba= np.apply_along_axis(vecinos,1,m_nearest)`

`m_neighbors = np.zeros(len(x))`
`def vecinos(near):`
 `   return m_neighbors[near]=1`
`prueba= np.apply_along_axis(vecinos,1,m_nearest)`

Después de conseguir tener en una matriz las posiciones del vecino mas cercano, intento hacerlo sin for pero no consigo que me funcione, nose si vosotros podreis ver donde esta el error.

Lo he probado con lambda y definiendo una función pero ninguna de las dos me funciona.

**Comment by alvarag** [comment]
Tienes varios problemas:

- ¿Dónde defines m_neighbors? Debería ser dentro de la función, ¿no?
- La asignación no devuelve nada, por lo que no puedes hacer return de ello.

Conclusión:
```
import numpy as np
from sklearn.metrics.pairwise import euclidean_distances
x=np.array([[1,2],[2,4],[2,2]])
z=np.array([[2,2],[2,4]])
euc_dis_func = lambda t: euclidean_distances([t],x).argmin()
dn_nn = lambda inst : np.apply_along_axis(euc_dis_func,1,[inst])
m_nearest=np.apply_along_axis(dn_nn,1,z)
m_nearest


def vecinos(near):
    m_neighbors = np.zeros(len(x))
    m_neighbors[near]=1
    return m_neighbors

prueba= np.apply_along_axis(vecinos,1,m_nearest)

prueba
```
