### ISSUE TITLE
Iteraciones sobre fit, predict y predict_proba

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#42]
Realizar un bucle para que fit predict y predict_proba se ejecuten un número de iteraciones en vez de una sola vez.
Fit: Con realizar un bucle que le haga ese número de iteraciones es suficiente
Predict: Hay que ir guardando los valores del fit y calcular el promedio 
Predict_proba: Hay que ir guardando los valores del fit y calcular el promedio

**Comment by Tulmot** [comment]
He subido el código con las iteraciones del fit, predict y predict_proba, el problema es que:

```
def predict(self, X):
        predictions=[]
        for classifiers in self._base_classifiers:
            predictions.append(self.base_estimator.predict(X))
        predictions=np.asarray(predictions)
        promedio=predictions.sum(axis=0)
        print(promedio)
```

self._base_classifiers, es el array que contiene los fit.
El problema es que nose como usarlo cuando llamo al predict que la clase base, y entonces siempre me esta cogiendo el mismo fit.

No se si me explicado bien

**Comment by alvarag** [comment]
¿Para que haces un bucle para recorrer tus estimadores bases si no luego no los utilizas en su interior? Creo que es bastante obvio...

**Comment by Tulmot** [comment]
Sisi, si ya se que obvio es, pero no puedo hacer classifiers.predict(X) porque entonces no llamo al predict de mi clase BaseDisturbingNeighbors...Supongo que seria algo así:
self.base_estimator.classifiers.predict(X), pero no se de que forma hacerlo para que lo haga correctamente

O sino como llamaría el predict de mi clase BaseDisturbingNeighbors usando los clasificadores?

**Comment by alvarag** [comment]
¿Por qué dices que al hacer classifiers.predict(X) no se llama al método predict de tu clase?

```
for classifier in self._base_classifiers:
            predictions.append(classifier.predict(X))
```

**Comment by Tulmot** [comment]
Porque entiendo que si no llamo a la clase, al tener esta clase un predict, se llamaría así misma.
Bueno y que lo probé y me daba error, ahora no me acuerdo cual. Mientras que si lo hago como he puesto si me lo hace bien pero siempre eligiendo el árbol el mismo árbol en mi caso.

**Comment by alvarag** [comment]
Habrá que revisar ese error que dices que te aparecía, entiendo que no debería.

Que siempre te haga siempre la misma predicción tiene sentido, porque el árbol de cada clasificador base es el mismo. En el fit de cada árbol, habrá que pasarle distinta semilla aleatoria a cada clasificador base que entrenas.

**Comment by Tulmot** [comment]
Después de comer le doy un repaso a ver si veo en donde puede estar el fallo y sino os pregunto.
