### ISSUE TITLE
Artículo Random Oracles

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#48]
Documentación sobre Random Oracles.

**Comment by Tulmot** [comment]
[pardo-rodriguez-diezpastor-garciaosorio_random-oracles-regression-ensembles.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1502984/pardo-rodriguez-diezpastor-garciaosorio_random-oracles-regression-ensembles.pdf)
[rodriguez-diezpastor-garciaosorio_random-oracle-ensembles-for-imbalanced-data.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1502985/rodriguez-diezpastor-garciaosorio_random-oracle-ensembles-for-imbalanced-data.pdf)
[rodriguez-kuncheva_naive-bayes-ensembles-random-oracle.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1502986/rodriguez-kuncheva_naive-bayes-ensembles-random-oracle.pdf)
[kuncheva-rodriguez_classifier-ensembles-random-linear-oracle.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1502987/kuncheva-rodriguez_classifier-ensembles-random-linear-oracle.pdf)

**Comment by jjrodriguez** [comment]
Antes de subir un artículo y dejarlo accesible a cualquiera, deberías
comprobar si tienes permisos para hacerlo.

**Comment by Tulmot** [comment]
Tienes razón, perdón pensé que como los artículos de Disturbing Neighbors me los subisteis, estos los subí sin preguntar, los he borrado, si tengo permisos me dices y los vuelvo a subir.
Lo siento de verdad.

**Comment by jjrodriguez** [comment]
OK, no debería yo haber subido los otros.
