### ISSUE TITLE
Fit Random Oracles

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#49]
Creamos el fit y las funciones necesarias para su correcto funcionamiento

**Comment by Tulmot** [comment]
Tengo una pregunta en este solo tengo X no tengo y, mi duda es entonces cuando llamo al fit de un clasificador, hay que pasarle X e y, pero como mi random_oracle solo tiene X no puedo hacerlo.

Nose si se me explicado, subo el código y si podeis mirarlo a ver el fit del BaseRandomOracles como debería hacerlo.

**Comment by alvarag** [comment]
SIEMPRE que se quiera entrenar un clasificador (aprendizaje supervisado) necesita X e y. ¿Cómo sino va a aprender la relación entre las entradas (X) y las salidas (y)?

**Comment by Tulmot** [comment]
Vamos que entonces la y aunque no la use para nada, se la paso para poder hacer el fit, vale vale, es que no me quedo muy claro eso.

**Comment by alvarag** [comment]
¿Y cómo vas a entrenar los clasificadores base sin la y? En el fit vas a "partir" el conjunto de entrenamiento en dos o más subconjuntos (selección aleatoria de oráculos, similar a lo que hacías con los disturbing) y con cada uno de ellos vas a entrenar un clasificador. Luego en el predict, comparas a ver cuál es el oráculo más cercano y utilizas el clasificador correspondiente para hacer la predicción.

**Comment by Tulmot** [comment]
es que entendi que la y no la tenia que pasar porque solo tenia que usar la X, pero como dices sino no podría entrenar el clasificador.
