### ISSUE TITLE
Leer artículo Disturbing Neighbours

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#5]
Para documentarnos sobre el método Disturbing Neighbours el profesor nos proporciona un artículo.

**Comment by jjrodriguez** [comment]
Estos son lo artículos donde se describe el método:

[maudes-rodriguez-garciaosorio_disturbing-neighbors-diversity-decision-forest.pdf](https://github.com/Tulmot/Proyecto-Python/files/1310630/maudes-rodriguez-garciaosorio_disturbing-neighbors-diversity-decision-forest.pdf)
[maudes-rodriguez-garciaosorio_disturbing-neighbors-ensembles-linear-svm.pdf](https://github.com/Tulmot/Proyecto-Python/files/1310631/maudes-rodriguez-garciaosorio_disturbing-neighbors-ensembles-linear-svm.pdf)
[rodriguez-maudes-pardo-garciaosorio_disturbing-neighbors-ensembles-regression.pdf](https://github.com/Tulmot/Proyecto-Python/files/1310633/rodriguez-maudes-pardo-garciaosorio_disturbing-neighbors-ensembles-regression.pdf)
