### ISSUE TITLE
Predict Random Oracles

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#50]
Realizar el método predict

**Comment by Tulmot** [comment]
El predict en mi caso como tengo 3 oracles me devuelve una lista con 3 arrays de arrays, cada arrays de arrays contiene el predict de su clasificador 

![imagen](https://user-images.githubusercontent.com/30071903/33621854-6818f520-d9ec-11e7-83cf-8440f824feed.png)

No se si esta bien tener el predict de cada clasificador por separado o deberia juntarlos y solo tener una lista de arrays

**Comment by jjrodriguez** [comment]
Primero una cuestión de terminología: no tienes 3 oráculos. Tienes un oráculo que asigna una de tres regiones.

La estructura de lo que te devuelve el predict no tiene que depender de cuantas regiones tengas. Tiene que tener la misma estructura que tenía para el DN.

Luego tendrás que hacer lo de las iteraciones. ¿Cómo combinarías varias listas de 3 arrays de arrays?

El orden en el que devuelves las predicciones del predict tiene que corresponder con el orden en el que te llegan las instancias.

**Comment by Tulmot** [comment]
vale entiendo, si que no se podrían combiar esas listas

> El orden en el que devuelves las predicciones del predict tiene que corresponder con el orden en el que te llegan las instancias.

Entonces como lo tengo hecho yo no me vale porque lo tengo ordenado según la región, ahora lo cambio entonces.

gracias
