### ISSUE TITLE
Método score iteraciones

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#53]
Hacer correctamente el método score cuando hacemos iteraciones.

**Comment by Tulmot** [comment]
Tengo una duda como debo llamar desde mi DisturbingNeighbors a mi BaseDisturbingNeighbors con el método score?
Porque desde donde lo pruebo cuando llamo al método lo hago así:
`scores = cross_val_score(dn, X, y, cv=5)`
Entonces nose como llamar a mi método score de BaseDisturbingNeighbors para luego calcular el promedio de los score segun las iteraciones.

**Comment by alvarag** [comment]
Del mismo modo que llamas a los de predicción: una llamada a cada método base (acumulándolo) y luego la media.

**Comment by Tulmot** [comment]
mmm vale, entonces seria poniendo `loquesea.score(X,y)`
