### ISSUE TITLE
Avanzar en la documentación

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#56]
La documentación está bastante atrasada, creo que debes empezar ya con ella. Te he hecho anotaciones sobre los PDF.
[anexosC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1510531/anexosC.pdf)
[memoriaC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1510532/memoriaC.pdf)

**Comment by Tulmot** [comment]
he avanzado sobre todo en el apartado de conceptos teóricos en la parte de la memoria, y en la parte de planificación en la parte del anexo
