### ISSUE TITLE
Rotation Forest dividir

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#66]
Dividimos el conjunto de datos(X) en grupos de 3, usamos permutaciones para evitar repetidos.

**Comment by Tulmot** [comment]
Se que dijimos hacerlo con permutaciones, pero me parece más facil crear una lista con el tamaño de las instancias y luego con shuffle barajarla y ya voy recorriendo la lista cogiendo de 3 en 3 posiciones.
Podría valer esto?

```
        self.random_state = check_random_state(self.random_state)
        tam = X.shape[0]
        l=np.arange(tam)
        self.random_state.shuffle(l)
        l=list(l)
        while(len(l)%self.n_groups!=0):
            l.append(self.random_state.randint(0,tam))
        l=np.asarray(l)
        a=np.split(l, l.shape[0]/self.n_groups)
```
La salida:
![imagen](https://user-images.githubusercontent.com/30071903/34009690-2331d862-e10a-11e7-8dc2-7e3cc64b3679.png)

**Comment by jjrodriguez** [comment]
Lo que hace shuffle es crear una permutación aleatoria.

**Comment by Tulmot** [comment]
vale, es que igual queriais que utilizara la función de permuta, entonces lo dejo así
