### ISSUE TITLE
Comentar correctamente las clases

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#71]
Repasa las clases y asegúrate de que todas están correctamente comentadas. Ejemplos:

- BaseRandomOracles: no tiene comentario al inicio de la clase.
- En general: no tienen comentarios más que al inicio de los métodos. Creo que hay algunas cosas que haces que igual merecen un comentario adicional en línea.

**Comment by Tulmot** [comment]
De momento comentadas los métodos DN y RO, y de este último he creado una nueva función para quitar el código repetido de predict y predict_proba

**Comment by alvarag** [comment]
Recuerda asignar horas a todas las tareas (incluídas las que te abrimos nosotros).
