### ISSUE TITLE
Predict RF

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#74]
Programar el método predict de Rotation Forest

**Comment by Tulmot** [comment]
Para hacer el predict entiendo que tendría que ir recorriendo los pcas para luego ir haciendo los transform a cada correspondiente subgrupo, es decir por ejemplo al primer subgrupo le hare el transfor con el primer pca no?

**Comment by alvarag** [comment]
Si, se trata de hacer algo "similar" a lo que estás haciendo en el train. Pero no tienes que volver a entrenar PCA ni coger nueva permutación para los grupos de atributos (porque ya lo tienes guardado)

**Comment by Tulmot** [comment]
Claro pero entonces la cosa es que tengo que recorrer el array con los subgrupos y el array con los pcas a la vez, el problema de eso que a un map solo puede hacerlo de uno en uno...entonces solo se me ocurre hacerlo con un for....

```
def predict(self, X):
        """Predict class for X.
        The predicted class of an input sample is computed as the class with
        the highest mean predicted probability.
        Parameters
        ----------
        X : It's a matrix of form = [n_instances, n_features]
            The training input samples. Sparse matrices are accepted only if
            they are supported by the base estimator.
        Returns
        -------
        y : It's a matrix of form = [n_class]
            The predicted classes.
        """
        
        split_group = self.split(X)
        for i in range(len(split_group)):
            self._pcas[i].transform(split_group[i])
```

Algo así

**Comment by alvarag** [comment]
Una solución que se me ocurre es crear una lista de tuplas, cada tupla tendrá el nº del grupo al que pertenece y el grupo (matriz de nx3).

```
list(zip(range(num_instances), groups))
```

La función recibirá una tupla formada por nº grupo y matriz nx3. Devolverá el transform del pca del nº de grupo que le haya llegado.

No sé si me he explicado bien.

**Comment by Tulmot** [comment]
Sisi entendido.

```
def pca_transform(pos_subX):
       return self._pcas[pos_subX[0]].transform(pos_subX[1])
split_group = self.split(X)
tuple_pos_subX=list(zip(range(len(self._pcas)),split_group))
pcas_transform=list(map(pca_transform, tuple_pos_subX))
pcas_transform = np.concatenate((pcas_transform),axis=1)
return self.base_estimator.predict(pcas_transform)
```

De esta forma me ha quedado el código y funciona correctamente gracias por la idea de la tupla.
