### ISSUE TITLE
Seleccionar una muestra RF

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#78]
Seleccionamos un muestra de cada uno de los subgrupos, por defecto el tamaño de dicha muestra será del 75% de los datos.
Dicha muestra la usaremos para entrenar pero para transformar le pasaremos el subgrupo entero.

**Comment by Tulmot** [comment]
Una pregunta yo ya tengo la muestra de cada subgrupo:

```
def sample(subX):
            tam_sample=round(subX.shape[0]*self.n_muestras)
            rnd_sample = np.arange(subX.shape[0])
            np.random.shuffle(rnd_sample)
            rnd_sample=rnd_sample[:tam_sample]
            return subX[rnd_sample[:]]
```
donde subX es cada uno de los subgrupos y n_muestras es el porcentaje del subgrupo que voy a coger.

Una de las preguntas es que como para cada uno de los subgrupos no quiero coger siempre las mismas filas no he usado el `self.random_state.shuffle(rnd_sample)` porque entiendo que sino siempre cogeria las mismas filas por eso `np.random.shuffle(rnd_sample)` para que me devuelva para cada subgrupo una diferente.

La otra duda es que ahora cuando ya tengo cada una de las muestras lo que hago es entrenarlas con pca.fit pero luego para hacer el pca.transform lo haria sobre la muestra que acabo de entrenar o tendria que coger el subgrupo entero?

**Comment by alvarag** [comment]
No reinventes la rueda... http://scikit-learn.org/stable/modules/generated/sklearn.utils.resample.html

Siempre tienes que utilizar una semilla que tu controles, acuérdate de cómo hicimos en el ensemble: pasar como semilla el número aleatorio que nos daba el generador aleatorio.

**Comment by jjrodriguez** [comment]
El pca.transform hay que hacerlo para todas las instancias.

**Comment by Tulmot** [comment]
vale gracias con eso ya puedo avanzar.

**Comment by Tulmot** [comment]
al final el fit me ha quedado de esta manera:

```
def fit(self, X, y):
        """Build a Bagging ensemble of estimators from the training set (X, y).
        Parameters
        ----------
        X : It's a matrix of form = [n_instances, n_features]
            The training input samples. Sparse matrices are accepted only if
            they are supported by the base estimator.
        y : It's a matrix of form = [n_class]
            The target values (class labels in classification, real numbers in
            regression).
        Returns
        -------
        self : object
            Returns self.
        """        
        def sample(subX):
            return resample(subX, n_samples = round(
                    subX.shape[0] * self.n_muestras))
        def pca_fit(samples):
            pca = decomposition.PCA(random_state=self.random_state)
            return pca.fit(samples)
        def pca_transform(pos_subX):
            return self._pcas[pos_subX[0]].transform(pos_subX[1])
        self.random_state = check_random_state(self.random_state)
        self._rnd_features=self._calc_rnd_features(X)
        split_group = self.split(X)
        sample_group = list(map(sample, split_group))
        self._pcas=list(map(pca_fit,sample_group))
        tuple_pos_subX=list(zip(range(len(self._pcas)),split_group))
        pcas_transform=list(map(pca_transform, tuple_pos_subX))
        pcas_transform = np.concatenate((pcas_transform),axis=1)
        self.base_estimator.fit(pcas_transform,y)
```

Me faltaría lo que me dijo ayer Alvar que `return self._pcas[pos_subX[0]].transform(pos_subX[1])` en vez de devolver asi la tuplas con [0] o [1], hacerlo de otra forma pero no he sabido como conseguirlo.

**Comment by alvarag** [comment]
Lo que te comentaba era esto:

```
def pca_transform(pos, subX):
            return self._pcas[pos].transform(subX)
```

Y cuando lo quieras utilizar:

```
pcas_transform=list(map(pca_transform, *tuple_pos_subX))
```

**Comment by Tulmot** [comment]
entiendo que lo que hace el * es pasarte los valores de la tupla por separado? por eso la función recibe los dos valores?

**Comment by alvarag** [comment]
Exacto, echa un ojo a este enlace: http://interactivepython.org/runestone/static/pip2/Tuples/TupleAssignmentwithunpacking.html

**Comment by Tulmot** [comment]
lo he probado y me falla me dice esto:


  File "C:\Users\Tubi\Desktop\eduard\Clase\TFG\base_rotation_forest.py", line 75, in fit
    pcas_transform=list(map(pca_transform, *tuple_pos_subX))

TypeError: pca_transform() takes 2 positional arguments but 4 were given

igual sobre un map no funciona?

**Comment by alvarag** [comment]
Si, por lo que veo no se comporta como yo esperaba con un ejemplo como este que muestro. Investiga un poco a ver si se puede hacer y, sino, lo dejas como lo tienes.

```
a = ((1, 2), (5,6))
def f (a, b): return a+b
list(map(f, *a))
```

**Comment by Tulmot** [comment]
vale voy a probar en un notebook a ver
