### ISSUE TITLE
Incluir referencias en la documentación

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#79]
He visto que casi no tienes ninguna referencia todavía en la memoria/anexos. Ten en cuenta que un documento como este debe constar de un número significativo de referencias (de hecho tienes varios artículos que ya deberían estar ahí para referenciarlos en conceptos teóricos).

Aquí tienes un manual por si te surgen dudas: https://es.sharelatex.com/learn/Bibliography_management_with_bibtex#!#Bibliography_management_with_Bibtex

**Comment by Tulmot** [comment]
Incluidas referencias en Conceptos teóricos y Técnicas y herramientas.
