### ISSUE TITLE
Seleccionar una instancias en base a las clases

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#80]
Lo primero elegimos las distintas clases(y), despues elegimos aleatoriamente una muestra de esas las distintas clases, y por ultimo seleccionamos del conjunto de datos(X) las instancias correspondientes a la muestra de esas clases.

**Comment by alvarag** [comment]
Tras lo que hemos visto hoy (sobre los map), creo que te debería resultar sencillo hacerlo funcional. No obstante, si quieres hazlo primero secuencial si te es más fácil y luego vemos juntos como hacerlo funcional.
