### ISSUE TITLE
Evitar código duplicado en los notebooks

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#81]
La creación del conjunto de datos, la asignación de la semilla y la división del conjunto de datos en entrenamiento y test deben estar una única vez, y no repetidas en cada casilla de cada clasificador

**Comment by alvarag** [comment]
Nota adicional, ¿a ti te funcionan los notebooks tal y como los tienes? (en la carpeta notebooks). Supongo que te estará diciendo que no encuentra sklearn_ubu.
Creo que los notebooks deberían estar en el directorio padre, donde está el paquete sklearn_ubu.

**Comment by alvarag** [comment]
En el notebook donde lee de flags.arff, deberá estar subido el data set para que nos pueda funcionar.

**Comment by Tulmot** [comment]
Esta tarde lo miro.

**Comment by Tulmot** [comment]
ya hecho los cambios deberia funcionar correctamente.
(A mi si me funciona)
