### ISSUE TITLE
Funcional RF

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#82]
Hacemos funcional el método fit de Rotation Forest

**Comment by Tulmot** [comment]
Estaba haciendo lo que dijimos ayer para lo del set de convertir las listas el tuplas para poder hacer luego el set.
He hecho un ejemplo:

```
lista=[]
def prueba(arr):
    lista.append(tuple(arr))
a=[[1,2], [2,3], [1,2]]
list(map(prueba,a))
print(set(lista))
```
Esto me devuelve:
`{(1, 2), (2, 3)}`
no se si os referíais hacer algo así, y ahora ya volver hacer una lista de listas?

si hay alguna forma de convertir el interior de la lista en tuplas sin tener que ir recorriendo de una en una me decís

**Comment by jjrodriguez** [comment]
Yo me refería a tener un conjunto de tuplas, porque no se puede tener un conjunto de listas. Y has obtenido un conjunto de tuplas.
No sé porque ahora quieres volver a tener una lista de listas.
Lo que hay que hacer es de ese conjunto quedarse con un subconjunto aleatorio.
Y entonces del conjunto de datos te quedas solo con los que aparezcan en el conjunto.

El código que tienes se puede simplificar:
```
a=[[1,2], [2,3], [1,2]]
print({tuple(x) for x in a})
```
