### ISSUE TITLE
Dibujar gráficas

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#86]
En Jupyter dibujamos las gráficas de cada uno de los algoritmos (DN, RO, RF), para ver como se divide el conjunto de datos.

**Comment by Tulmot** [comment]
![imagen](https://user-images.githubusercontent.com/30071903/34492389-a40c70dc-efe7-11e7-8cc8-5b03a3d4ab40.png)

Algo así sería?

**Comment by jjrodriguez** [comment]
El conjunto de entrada tiene que ser multi-label. No me queda claro que este lo sea, veo dos colores (azul y rojo) aunque con dos tonos cada uno.

Si es multi-label, al dibujar los clasificadores deberíamos tener más de dos colores.

Aunque quizás de momento estás probando sin multi-label.

En Disturbing Neighbors las fronteras no deberían ser siempre paralelas a los ejes.

Para un mismo conjunto de datos puedes dibujar distintos clasificadores del mismo tipo, usando distintas semillas aleatorias.

**Comment by Tulmot** [comment]
estaba probando sin multi-label, es que con multi-label me falla, voy a ver si veo el fallo y sino subo el código a ver si lo veis vosotros.

vamos que dibuje varios Disturbing Neighbors por ejemplo cada uno con una semilla aleatoria

**Comment by Tulmot** [comment]
He subido dentro de la carpeta sklearn-ubu un .py con el nombre "sin titulo 0" (No le he puesto nombre porque lo borrare), si podeis mirar a ver si vosotros veis porque puede fallar el DIsturbing Neighbors si le paso el multi-label.

**Comment by Tulmot** [comment]
Funciona para single-label
