### ISSUE TITLE
Limpiar y sanear el repositorio

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#88]
En el repositorio hay elementos que no deberían estar o deberían estar revisados

- PrimerCodigo, PruebaDN... entiendo, como su nombre indica, que ya no tiene sentido que estén ahí.
- La mayor parte de los notebooks están en inglés, pero hay uno que no y alguna frase de los otros.
- El tema del idioma también se da en parte de las clases del repositorio.
- Asegurarse de que todo el código cumple las normas de estilo PEP.

**Comment by Tulmot** [comment]
> El tema del idioma también se da en parte de las clases del repositorio.

Con esto entiendo que te refieres a que por ejemplo el nombre de los notebook tendrían que estar en inglés?

**Comment by alvarag** [comment]
Además de eso, que también en las clases (RandomOracles.py u otras) hay algunos comentarios/variables en inglés. Revisa bien todo.

**Comment by Tulmot** [comment]
Ya está todo los comentarios en ingles excepto las clases privadas.
RandomOracles.py entiendo que lo que quieres es que ponga un comentario? porque esas no tienen, pero tampoco se que poner porque solo contienen el init que es que el luego llama al base
