### ISSUE TITLE
Jupyter

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#89]
Intento desde la consola abrir jupyter:
![imagen](https://user-images.githubusercontent.com/30071903/34417108-fe92c2c6-ebf6-11e7-820e-68e62343136d.png)
He probado a reiniciar el ordenador pero sigue igual, no se si sabreis vosotros porque puede ser o si me podeis dar alguna idea de como solucionarlo.
He mirado por internet pero no veo como resolverlo.

**Comment by jjrodriguez** [comment]
Lo único que se me ocurre es reinstalar anaconda.

**Comment by Tulmot** [comment]
El problema que veo es que me dejara reinstalar en la misma carpeta? 
Porque sino luego no tendre algún conflicto de rutas con lo que tengo ahora?

**Comment by jjrodriguez** [comment]
Si te da problemas al reinstalar en la misma carpeta, puedes desinstalar antes. Y borrar la carpeta si no lo hace al desinstalar.

Se debería poder instalar en varias carpetas, tendrías que configurar las rutas.

**Comment by Tulmot** [comment]
vale voy a acabar una cosa de la memoria y pruebo a ver

**Comment by Tulmot** [comment]
Al final ha sido que el antivirus no sé porque el archivo de python.exe me lo había detectado como amenaza y lo tenía bloqueado, ahora ya funciona correctamente.
