### ISSUE TITLE
SingleLabel para Random Oracles

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#91]
Los clasificadores ahora mismo solo funcionan para casos multilabel, y queremos que también funcionen para casos singlelabel.

**Comment by Tulmot** [comment]
Me sale error en:

`if((min(prediction_proba, key=(lambda x: len(x[0])))).shape[1]):
`
TypeError: object of type 'numpy.float64' has no len()

nose muy bien como corregirlo

Nota: No he subido todo el código porque lo podeis ver en base_random_oracles

**Comment by alvarag** [comment]
Lo que quieres saber es si es de tipo array o no, por lo que tendrás que comprobar el tipo que te devuelve la función. Lo que no puedes hacer es intentar acceder a una propiedad de un array si lo que tienes es un número.
Pista: https://stackoverflow.com/questions/152580/whats-the-canonical-way-to-check-for-type-in-python

**Comment by Tulmot** [comment]
Claro pero el problema es que yo hago esto por ejemplo:

`if(type(min(prediction_proba, key=(lambda x: len(x[0])))) == np.ndarray):`

Y claro esto me devuelve true si es un ndarray que es lo que me devuelve TRUE cuando es multilabel y FALSE cuando es singlelabel

El problema es que esto cuando es single falla porque un float no tiene _len()_, entonces nose como prodria cambiar esto, ya que la comprobación debería hacerla de otra manera para no utilizar _len()_

**Comment by alvarag** [comment]
En cualquier momento (incluso al iniciar train), tu puedes saber si se trata de un conjunto multi-label o no: fijándote en si el primer elemento de *y* es o no un array.

**Comment by Tulmot** [comment]
Lo que hecho como predict o predict_proba no reciben la _y_, en fit creo una variable global(self), y hay la doy el valor 0 si es single label y 1 si es multilabel.

Así funciona correctamente, sería válido hacerlo así?

**Comment by alvarag** [comment]
Veo más lógico una variable booleana... Pero desde mi punto de vista sí podría ser una solución, no sé si Juanjo habrá pensado en algo más "elegante"

**Comment by Tulmot** [comment]
También es verdad que si solo puede tomar dos valores mejor booleana, cierro el tema y ya si luego Juanjo da una idea mejor lo cambio.
