### ISSUE TITLE
Correcciones sobre la memoria

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#93]
Adjunto los documentos de memoria y anexos comentados. Hay varias cosas en las que debes prestar atención:

- Trata de crear primero la estructura que quieres transmitir y luego la "rellenas" de contenido. De este modo te servirá para aclarar las ideas y organizar el documento.
- Antes de puntos y seguido, comas y paréntesis se te olvida el espacio.
- Siempre entre la palabra de la cita y la cita en sí misma pon ~ (espacio no separable).
- Lee dos veces cada párrafo y piensa que lo tiene que entender alguien que no tiene tus conocimientos en algunos conceptos.
- Siempre que nombres un método, como puede ser *fit*, debe poderse diferenciar del resto del texto. En mi opinión, utilizar una fuente monoespaciada puede ser la mejor solución \texttt{...}.

Saludos,

[anexosC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1606495/anexosC.pdf)
[memoriaC.pdf](https://github.com/Tulmot/Sklearn-Multilabel/files/1606496/memoriaC.pdf)

**Comment by Tulmot** [comment]
Tengo algunas dudas en la parte del anexo:

- Con lo de producto/elemento de Scrum que hace referencia a cada Milestone, issue...no entiendo muy bien que poner.

- Espacios solo se ponen antes del espacio no?, en los puntos o comás solo se pone espacio después.

**Comment by alvarag** [comment]
La idea es definir explícitamente a qué elemento de Scrum hace referencia el elemento de Github que estás usando, ej:  cada Milestone se corresponderá con un Sprint, todas las tareas de un milestone serán el Sprint Backlog, etc.

**Comment by alvarag** [comment]
Si, respecto a los espacios en blanco, antes de paréntesis y después de punto o coma.

**Comment by Tulmot** [comment]
Casi todas la correciones corregidas, lo que queda lo mejorare en el siguiente sprint.
