### ISSUE TITLE
Importar MAX_INT de sklearn

### ISSUE THREAD

**Issue by alvarag** [Tulmot/Sklearn-Multilabel#94]
En vez de definir MAX_INT, utilizar el que existe en sklearn:

```
from sklearn.ensemble.bagging import MAX_INT
```

Además, estás definiendo MAX_INT en un fichero .py donde luego no la utilizas.

**Comment by Tulmot** [comment]
Se me olvidó quitarle, lo utilizaba en la primera versión del método.
