### ISSUE TITLE
Corregir los notebook

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#96]
Corregir los notebook para que funcionen correctamente, ya que al descargarlos de github no encuentra bien las librerías.

**Comment by Tulmot** [comment]
El problema era el __init__.py, ahora ya funciona correctamente se supone,
si podéis descargaros vosotros el código a ver si ahora os funciona correctamente y me decías para cerrar o no la issue

**Comment by Tulmot** [comment]
He visto que solo me funciona correctamente en el notebook de sin iteraciones, el de con iteraciones y datos reales me sigue fallando
Es decir solo me importa bien los bases, los ensembles no pero no sé porque

**Comment by alvarag** [comment]
Me sucede lo mismo... yo creo que el __init__.py del interior del paquete no está bien formado

**Comment by alvarag** [comment]
Te comento la solución que he hecho y funciona (pero esto deberías haber llegado tu...):

Borra el __init__.py del directorio donde están los notebooks.

En el __init__.py del paquete sklearn_ubu:
```Python
from .base_disturbing_neighbors import BaseDisturbingNeighbors
from .base_random_oracles import BaseRandomOracles
from .base_rotation_forest import BaseRotationForest
from .disturbing_neighbors import DisturbingNeighbors
from .homogeneous_ensemble import HomogeneousEnsemble
from .random_oracles import RandomOracles
from .rotation_forest import RotationForest
```

Cuando quieras utilizar una clase que está en otro .py, ej: DisturbingNeighbors

```Python
from .homogeneous_ensemble import HomogeneousEnsemble
from .base_disturbing_neighbors import BaseDisturbingNeighbors

class DisturbingNeighbors(HomogeneousEnsemble):
```

**Comment by Tulmot** [comment]
No entendido la segunda parte, es decir en la clase DisturbingNeighbors por ejemplo que en los from ponga antes un "."
No se si te refieres a eso, pero a mi asi no me funciona.

**Comment by alvarag** [comment]
Si, de hecho el __init__.py lo puedes dejar vacío como lo tenías que no es necesario incluir nada.

Cuando quieras importar un fichero que está en el mismo directorio que el .py, hay que poner "." delante del nombre para indicar que está en el mismo directorio.

**Comment by Tulmot** [comment]
Vale es que si dejaba lo del init me daba problemas, al dejarlo vacío me funciona bien.
