### ISSUE TITLE
Correciones menores

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#97]
Corregir fallos menores, entre ellos:

- En Rotation Forest utilizar el conjunto reducido segun las clases(instance_classes)

- En Ramdon Oracles ver porque no funciona al dibujar la gráfica

- En las clases ensemble modificar el base_estimator

**Comment by Tulmot** [comment]
Sobre el base_estimator de los ensembles, os referiais a algo así?
```
from .homogeneous_ensemble import HomogeneousEnsemble
from .base_disturbing_neighbors import BaseDisturbingNeighbors
from sklearn.tree import DecisionTreeClassifier

class DisturbingNeighbors(HomogeneousEnsemble):

    def __init__(self,
                 base_estimator_=DecisionTreeClassifier(),
                 n_estimators=10,
                 random_state=None,
                 estimator_params=tuple()):
        self.base_estimator_ = BaseDisturbingNeighbors(base_estimator_)
        self.n_estimators = n_estimators
        self.random_state = random_state
        self.estimator_params = estimator_params  
```

**Comment by alvarag** [comment]
La idea es esa, pero comprueba que esté haciendo lo que quieres en los dos casos:

- Cuando le pasas un estimador base.
- Cuando no se lo pasas.

**Comment by Tulmot** [comment]
Pues si que funciona de las dos maneras, lo que me falla es cuando hago la validación cruzada:

![imagen](https://user-images.githubusercontent.com/30071903/34731002-466276dc-f561-11e7-83b0-266578d0bc1e.png)

Me da problemas con el constructor...

**Comment by alvarag** [comment]
Si falla en la validación cruzada es que no lo puedes hacer así, fíjate que en el error que muestras tienes un BaseDisturbingNeighbors(BaseDisturbingNeighbors(DecisionTreeClassifier)), es como que hay un anidamiento extra.

**Comment by Tulmot** [comment]
![imagen](https://user-images.githubusercontent.com/30071903/34839773-14a627f8-f703-11e7-804e-f6c41256b022.png)

Como podeis apreciar en la foto el Disturbing Neighbors, es muy parecido al Random Oracles, nose si es normal que se parezcan tanto, o con lo de la foto no se puede apreciar

**Comment by jjrodriguez** [comment]
Creo que se diferencian lo suficiente. Podrías dibujar varios del mismo tipo para cada conjunto de datos, cambiando la semilla aleatoria, para ver como se diferencian entre ellos. También podrías dibujar un árbol por si solo.

Lo que no me cuadra es que las decisiones sean todas paralelas a los ejes. Especialmente en el Random Oracles. En el DN cabe la posibilidad de que los atributos añadidos no sean seleccionados, pero en el RO tendría que haber una división que es muy improbable que sea paralela.

**Comment by Tulmot** [comment]
Vale, voy a dibujar el árbol a ver que veo.

**Comment by jjrodriguez** [comment]
En los Random Oracles debería haber dos árboles, podrías dibujar ambos (tanto las superficies de decisión como los propios árboles).

**Comment by Tulmot** [comment]
El problema es que me dice que:
AttributeError: 'BaseRandomOracles' object has no attribute 'tree_'

Como puedo hacer para que pueda dibujar arboles?

Ahora mismo en  baserandomoracles uso el base estimator del decisiontreeclassfier y esto es lo que me devuelve el fit:

```
BaseRandomOracles(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best'),
         n_oracles=3,
         random_state=<mtrand.RandomState object at 0x000001D80B5DF090>)
```

**Comment by jjrodriguez** [comment]
En un RandomOracle tienes que tener varios clasificadores base. Estarán almacenados en algún atributo del objeto que tendrá algún nombre. Puedes hacer un método que reciba un índice y te devuelva el clasificador correspondiente.

**Comment by Tulmot** [comment]
He comprobado una cosa según entiendo que cuando hacia classifier.fit, ya entrenaba el clasificador no hacia falta guardarlo en ninguna variable, pero si lo guardo en una variable(como tenía) si me dibuja los árboles.
La differencia la veo que al guardarlo en una variable me guarda:
```
BaseRandomOracles(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=0, splitter='best')
```
Y si no lo guardo pues me devuelve lo de arriba por eso falla al dibujar el árbol

**Comment by Tulmot** [comment]
Voy hacer como has dicho para los ensembles de cuando tengo varios clasificadores base

**Comment by alvarag** [comment]
A ver si organizamos conceptos, que no me está quedando claro el problema.

```
ensemble = RandomOracle()
ensemble.fit(X, y)
```
Tras este código, la variable ensemble es un RandomOracle entrenado con X e y. Independientemente de lo que devuelvas en la función fit.

Si tu devuelves en el fit un árbol, pues tendrás un árbol fuera; si no devuelves nada, tendrás None, ¿no?

No sé si es que no te he entendido

**Comment by Tulmot** [comment]
No no, no me refería a eso,
es que a la hora de cuando voy  a dibujar el árbol
```
dot_data = export_graphviz(classifier_train, out_file=None)
graph = graphviz.Source(dot_data)
```
Cuando hago :
`classifier_train = classifier.fit(X_train, y_train)`

Me funciona correctamente mientras que si hago:
```
dot_data = export_graphviz(classifier, out_file=None)
graph = graphviz.Source(dot_data)
```
`classifier.fit(X_train, y_train)`

Me falla.
Es decir si guardo el clasificador entrenado en una variable me funciona si no, no.

**Comment by alvarag** [comment]
¿Pero qué devuelves en el método fit? ¿El propio clasificador u otra cosa?

Si lo común es devolver en sklearn self en fit, eso es lo que debes devolver.

**Comment by Tulmot** [comment]
sisi en sklearn se devuelve el estimador.fit, yo devuelvo lo mismo.

**Comment by alvarag** [comment]
¿Y ese código está subido? Porque yo no veo que se devuelva nada en el fit.

**Comment by alvarag** [comment]
Por cierto, pon en n_estimators por defecto a todos un valor: en rotation es 3 y en otros 10. Me parece que 10 es un buen número.

**Comment by Tulmot** [comment]
Ahora lo actualizo que no lo habia subido no
