### ISSUE TITLE
Comentar ensembles

### ISSUE THREAD

**Issue by Tulmot** [Tulmot/Sklearn-Multilabel#99]
Comentar los métodos ensembles, corregir los base, ya que estos no son ensembles

**Comment by Tulmot** [comment]
Los parametros hace falta que los comente?, lo digo porque como estan comentados en los clasificadores base, al final sería lo mismo.

**Comment by alvarag** [comment]
Los parámetros que reciben los clasificadores base son distintos a los que reciben los ensembles. Todos deben ser comentados.

Recuerda seguir lo más fielmente posible el estilo de sklearn, incluida la parte de referencias y pones el paper donde se presentó el método.
